name: TickVote
version: '1.1'
author: Murry Puppins
main: us.murrypuppins.tickvote.Main
api-version: '1.15'
depend: [Vault]

commands:
  tv:
    usage: /tv <argument>
    description: TickVote command
    permission: tv.vote
  tv reload:
    usage: /tv reload
    description: Reload config
    permission: tv.reload